"""Generates venue_geo.py: a deterministic (non-network) lat/lon per venue string.

Real street-level geocoding requires a network geocoding API, which the build
pipeline intentionally avoids (offline, reproducible builds). Instead each
venue is placed at a small deterministic offset from its chapter's city
center — enough to plot distinct markers on a per-chapter city map and see
which venues repeat, without depending on an external service.
"""
import json, glob, hashlib, os
from chapter_geo import CHAPTER_GEO

DASHBOARD_DIR = os.path.dirname(os.path.abspath(__file__))
ANALYSIS_DIR = os.path.dirname(DASHBOARD_DIR)
ENRICHED_DIR = os.path.join(ANALYSIS_DIR, 'enriched')
OUTPUT_FILE = os.path.join(DASHBOARD_DIR, 'venue_geo.py')

# Degrees of jitter (~ a few km at mid latitudes) so distinct venues in the
# same city don't overlap on the map.
JITTER_DEG = 0.03


def chapter_slug(fname):
    return fname.replace('-dbt-meetup-group.json', '').replace('-dbt-meetup.json', '').replace('.json', '')


def deterministic_offset(key):
    h = hashlib.sha256(key.encode('utf-8')).digest()
    dx = (int.from_bytes(h[0:4], 'big') / 0xFFFFFFFF - 0.5) * 2 * JITTER_DEG
    dy = (int.from_bytes(h[4:8], 'big') / 0xFFFFFFFF - 0.5) * 2 * JITTER_DEG
    return dx, dy


venues = {}  # (slug, venue_str) -> {lat, lon, name}

for path in sorted(glob.glob(f'{ENRICHED_DIR}/*.json')):
    fname = path.split('/')[-1]
    if fname.startswith('_'):
        continue
    slug = chapter_slug(fname)
    geo = CHAPTER_GEO.get(slug)
    if not geo or geo.get('lat') is None:
        continue
    data = json.load(open(path))
    for event in data.get('events', []):
        loc = (event.get('location') or '').strip()
        if not loc or 'online' in loc.lower():
            continue
        key = f'{slug}::{loc}'
        if key in venues:
            continue
        dx, dy = deterministic_offset(key)
        venue_name = loc.split(',')[0].strip()
        venues[key] = {
            'venue': loc,
            'name': venue_name,
            'lat': round(geo['lat'] + dy, 5),
            'lon': round(geo['lon'] + dx, 5),
        }

with open(OUTPUT_FILE, 'w') as f:
    f.write('# Generated by build_venue_geo.py - do not hand-edit.\n')
    f.write('# Deterministic per-venue coordinates jittered around each chapter\'s\n')
    f.write('# city center (no network geocoding). Keyed "<chapter_slug>::<venue address>".\n')
    f.write('VENUE_GEO = ')
    f.write(json.dumps(venues, indent=2, ensure_ascii=False))
    f.write('\n')

print(f'Wrote {len(venues)} venues to {OUTPUT_FILE}')
