import json, re, os

DASHBOARD_DIR = os.path.dirname(os.path.abspath(__file__))
ANALYSIS_DIR = os.path.dirname(DASHBOARD_DIR)
GROUPS_FILE = os.path.join(ANALYSIS_DIR, 'dbt-meetup-groups.json')
OUTPUT_FILE = os.path.join(DASHBOARD_DIR, 'chapter_names.py')

def slug_from_url(url):
    return url.rstrip('/').split('/')[-1]

def clean_name(name):
    name = re.sub(r'\s*dbt Meetup( Group)?\s*$', '', name, flags=re.IGNORECASE)
    return name.strip()

def build():
    groups = json.load(open(GROUPS_FILE))
    mapping = {}
    for g in groups:
        slug = slug_from_url(g['url'])
        norm_slug = slug.replace('-dbt-meetup-group', '').replace('-dbt-meetup', '')
        mapping[norm_slug] = clean_name(g['name'])
    return mapping

if __name__ == '__main__':
    mapping = build()
    with open(OUTPUT_FILE, 'w') as f:
        f.write('# Generated by build_chapter_names.py from dbt-meetup-groups.json - do not hand-edit.\n')
        f.write('# Maps chapter slug -> official Meetup.com group display name (dbt Meetup suffix stripped).\n')
        f.write('CHAPTER_DISPLAY_NAMES = ')
        json.dump(mapping, f, indent=4, ensure_ascii=False)
        f.write('\n')
    print(f'Wrote {len(mapping)} chapter display names to {OUTPUT_FILE}')
