CHAPTER_GEO = {
    "abuja": {
        "city": "Abuja",
        "country": "Nigeria",
        "lat": 9.0765,
        "lon": 7.3986,
        "online_only": True,
    },
    "amsterdam": {
        "city": "Amsterdam",
        "country": "Netherlands",
        "lat": 52.3676,
        "lon": 4.9041,
    },
    "analytics-engineering-belgium": {
        "city": "Leuven/Antwerp",
        "country": "Belgium",
        "lat": 50.8503,
        "lon": 4.3517,
    },
    "athens": {"city": "Athens", "country": "Greece", "lat": 37.9838, "lon": 23.7275},
    "atlanta": {"city": "Atlanta", "country": "USA", "lat": 33.7490, "lon": -84.3880},
    "austin": {"city": "Austin", "country": "USA", "lat": 30.2672, "lon": -97.7431},
    "bangalore": {
        "city": "Bangalore",
        "country": "India",
        "lat": 12.9716,
        "lon": 77.5946,
        "online_only": True,
    },
    "barcelona": {
        "city": "Barcelona",
        "country": "Spain",
        "lat": 41.3874,
        "lon": 2.1686,
    },
    "berlin": {"city": "Berlin", "country": "Germany", "lat": 52.5200, "lon": 13.4050},
    "bogota": {"city": "Bogotá", "country": "Colombia", "lat": 4.7110, "lon": -74.0721},
    "boise": {
        "city": "Boise",
        "country": "USA",
        "lat": 43.6150,
        "lon": -116.2023,
        "online_only": True,
    },
    "boston": {"city": "Boston", "country": "USA", "lat": 42.3601, "lon": -71.0589},
    "bratislava": {
        "city": "Bratislava",
        "country": "Slovakia",
        "lat": 48.1486,
        "lon": 17.1077,
    },
    "brisbane": {
        "city": "Brisbane",
        "country": "Australia",
        "lat": -27.4698,
        "lon": 153.0251,
    },
    "budapest": {
        "city": "Budapest",
        "country": "Hungary",
        "lat": 47.4979,
        "lon": 19.0402,
    },
    "buenos-aires": {
        "city": "Buenos Aires",
        "country": "Argentina",
        "lat": -34.6037,
        "lon": -58.3816,
    },
    "chicago": {"city": "Chicago", "country": "USA", "lat": 41.8781, "lon": -87.6298},
    "china": {
        "city": "China (online)",
        "country": "China",
        "lat": 35.8617,
        "lon": 104.1954,
        "online_only": True,
    },
    "cluj": {
        "city": "Cluj-Napoca",
        "country": "Romania",
        "lat": 46.7712,
        "lon": 23.6236,
        "online_only": True,
    },
    "copenhagen": {
        "city": "Copenhagen",
        "country": "Denmark",
        "lat": 55.6761,
        "lon": 12.5683,
    },
    "dallas": {"city": "Dallas", "country": "USA", "lat": 32.7767, "lon": -96.7970},
    "dc": {
        "city": "Washington DC (metro)",
        "country": "USA",
        "lat": 38.9072,
        "lon": -77.0369,
    },
    "denver": {"city": "Denver", "country": "USA", "lat": 39.7392, "lon": -104.9903},
    "detroit": {
        "city": "Detroit",
        "country": "USA",
        "lat": 42.3314,
        "lon": -83.0458,
        "online_only": True,
    },
    "dubai": {"city": "Dubai", "country": "UAE", "lat": 25.2048, "lon": 55.2708},
    "dublin": {"city": "Dublin", "country": "Ireland", "lat": 53.3498, "lon": -6.2603},
    "florianopolis": {
        "city": "Florianópolis",
        "country": "Brazil",
        "lat": -27.5954,
        "lon": -48.5480,
    },
    "halifax": {
        "city": "Halifax",
        "country": "Canada",
        "lat": 44.6488,
        "lon": -63.5752,
    },
    "helsinki": {
        "city": "Helsinki",
        "country": "Finland",
        "lat": 60.1699,
        "lon": 24.9384,
    },
    "ho-chi-minh-city": {
        "city": "Ho Chi Minh City",
        "country": "Vietnam",
        "lat": 10.8231,
        "lon": 106.6297,
    },
    "houston": {"city": "Houston", "country": "USA", "lat": 29.7604, "lon": -95.3698},
    "lagos": {"city": "Lagos", "country": "Nigeria", "lat": 6.5244, "lon": 3.3792},
    "london": {"city": "London", "country": "UK", "lat": 51.5072, "lon": -0.1276},
    "los-angeles": {
        "city": "Los Angeles",
        "country": "USA",
        "lat": 34.0522,
        "lon": -118.2437,
    },
    "madrid": {"city": "Madrid", "country": "Spain", "lat": 40.4168, "lon": -3.7038},
    "manila": {
        "city": "Manila",
        "country": "Philippines",
        "lat": 14.5995,
        "lon": 120.9842,
    },
    "marseille": {
        "city": "Marseille",
        "country": "France",
        "lat": 43.2965,
        "lon": 5.3698,
    },
    "medellin": {
        "city": "Medellín",
        "country": "Colombia",
        "lat": 6.2442,
        "lon": -75.5812,
    },
    "melbourne": {
        "city": "Melbourne",
        "country": "Australia",
        "lat": -37.8136,
        "lon": 144.9631,
    },
    "milan": {"city": "Milan", "country": "Italy", "lat": 45.4642, "lon": 9.1900},
    "minneapolis": {
        "city": "Minneapolis",
        "country": "USA",
        "lat": 44.9778,
        "lon": -93.2650,
    },
    "montreal": {
        "city": "Montreal",
        "country": "Canada",
        "lat": 45.5019,
        "lon": -73.5674,
    },
    "munich": {"city": "Munich", "country": "Germany", "lat": 48.1351, "lon": 11.5820},
    "norther-germany": {
        "city": "Hamburg/Hanover",
        "country": "Germany",
        "lat": 52.3759,
        "lon": 9.7320,
    },
    "nyc": {"city": "New York City", "country": "USA", "lat": 40.7128, "lon": -74.0060},
    "oslo-dbt-group": {
        "city": "Oslo",
        "country": "Norway",
        "lat": 59.9139,
        "lon": 10.7522,
    },
    "paris": {"city": "Paris", "country": "France", "lat": 48.8566, "lon": 2.3522},
    "perth": {
        "city": "Perth",
        "country": "Australia",
        "lat": -31.9505,
        "lon": 115.8605,
        "online_only": True,
    },
    "philadelphia": {
        "city": "Philadelphia",
        "country": "USA",
        "lat": 39.9526,
        "lon": -75.1652,
    },
    "phoenix": {"city": "Phoenix", "country": "USA", "lat": 33.4484, "lon": -112.0740},
    "portland": {
        "city": "Portland",
        "country": "USA",
        "lat": 45.5152,
        "lon": -122.6784,
    },
    "prague": {"city": "Prague", "country": "Czechia", "lat": 50.0755, "lon": 14.4378},
    "raleigh-d": {
        "city": "Raleigh-Durham",
        "country": "USA",
        "lat": 35.7796,
        "lon": -78.6382,
    },
    "rhein-ruhr": {
        "city": "Cologne (Rhein-Ruhr)",
        "country": "Germany",
        "lat": 50.9375,
        "lon": 6.9603,
    },
    "riyadh": {
        "city": "Riyadh",
        "country": "Saudi Arabia",
        "lat": 24.7136,
        "lon": 46.6753,
    },
    "salt-lake-city": {
        "city": "Salt Lake City",
        "country": "USA",
        "lat": 40.7608,
        "lon": -111.8910,
        "online_only": True,
    },
    "san-francisco": {
        "city": "San Francisco Bay Area",
        "country": "USA",
        "lat": 37.7749,
        "lon": -122.4194,
    },
    "sao-paulo": {
        "city": "São Paulo",
        "country": "Brazil",
        "lat": -23.5505,
        "lon": -46.6333,
    },
    "seattle": {"city": "Seattle", "country": "USA", "lat": 47.6062, "lon": -122.3321},
    "seoul": {
        "city": "Seoul",
        "country": "South Korea",
        "lat": 37.5665,
        "lon": 126.9780,
    },
    "singapore": {
        "city": "Singapore",
        "country": "Singapore",
        "lat": 1.3521,
        "lon": 103.8198,
    },
    "stockholm": {
        "city": "Stockholm",
        "country": "Sweden",
        "lat": 59.3293,
        "lon": 18.0686,
    },
    "swiss": {
        "city": "Zurich",
        "country": "Switzerland",
        "lat": 47.3769,
        "lon": 8.5417,
    },
    "sydney": {
        "city": "Sydney",
        "country": "Australia",
        "lat": -33.8688,
        "lon": 151.2093,
    },
    "taipei": {"city": "Taipei", "country": "Taiwan", "lat": 25.0330, "lon": 121.5654},
    "tel-aviv": {
        "city": "Tel Aviv",
        "country": "Israel",
        "lat": 32.0853,
        "lon": 34.7818,
    },
    "tokyo": {"city": "Tokyo", "country": "Japan", "lat": 35.6762, "lon": 139.6503},
    "toronto": {
        "city": "Toronto",
        "country": "Canada",
        "lat": 43.6532,
        "lon": -79.3832,
    },
    "uyo": {"city": "Uyo", "country": "Nigeria", "lat": 5.0377, "lon": 7.9128},
    "vancouver": {
        "city": "Vancouver",
        "country": "Canada",
        "lat": 49.2827,
        "lon": -123.1207,
    },
    "vienna": {"city": "Vienna", "country": "Austria", "lat": 48.2082, "lon": 16.3738},
    "vilnius": {
        "city": "Vilnius",
        "country": "Lithuania",
        "lat": 54.6872,
        "lon": 25.2797,
    },
    "wellington": {
        "city": "Wellington",
        "country": "New Zealand",
        "lat": -41.2865,
        "lon": 174.7762,
    },
}
