# Generated by build_venue_geo.py - do not hand-edit.
# Deterministic per-venue coordinates jittered around each chapter's
# city center (no network geocoding). Keyed "<chapter_slug>::<venue address>".
VENUE_GEO = {
  "amsterdam::JetBrains Amsterdam Terrace Tower office, Gelrestraat 16, Amsterdam": {
    "venue": "JetBrains Amsterdam Terrace Tower office, Gelrestraat 16, Amsterdam",
    "name": "JetBrains Amsterdam Terrace Tower office",
    "lat": 52.38264,
    "lon": 4.93202
  },
  "amsterdam::TicketSwap, Rokin 75-3, Amsterdam": {
    "venue": "TicketSwap, Rokin 75-3, Amsterdam",
    "name": "TicketSwap",
    "lat": 52.34178,
    "lon": 4.92519
  },
  "amsterdam::Motherduck HQ, Oostelijke Handelskade 749, Amsterdam": {
    "venue": "Motherduck HQ, Oostelijke Handelskade 749, Amsterdam",
    "name": "Motherduck HQ",
    "lat": 52.38779,
    "lon": 4.91815
  },
  "amsterdam::Snowflake Amsterdam Office, Gustav Mahlerlaan 300-314, Amsterdam": {
    "venue": "Snowflake Amsterdam Office, Gustav Mahlerlaan 300-314, Amsterdam",
    "name": "Snowflake Amsterdam Office",
    "lat": 52.33939,
    "lon": 4.88721
  },
  "amsterdam::Werkspot, Herengracht 469, Amsterdam": {
    "venue": "Werkspot, Herengracht 469, Amsterdam",
    "name": "Werkspot",
    "lat": 52.362,
    "lon": 4.91821
  },
  "amsterdam::Floryn, Walpoort 10, 's-Hertogenbosch": {
    "venue": "Floryn, Walpoort 10, 's-Hertogenbosch",
    "name": "Floryn",
    "lat": 52.37723,
    "lon": 4.912
  },
  "amsterdam::Nimbus Intelligence, Haaksbergweg 75, Amsterdam": {
    "venue": "Nimbus Intelligence, Haaksbergweg 75, Amsterdam",
    "name": "Nimbus Intelligence",
    "lat": 52.39026,
    "lon": 4.87487
  },
  "amsterdam::Miele X, Beethovenstraat 517, Amsterdam": {
    "venue": "Miele X, Beethovenstraat 517, Amsterdam",
    "name": "Miele X",
    "lat": 52.39025,
    "lon": 4.92731
  },
  "amsterdam::Xebia Amsterdam, Wibautstraat 200/202, Amsterdam": {
    "venue": "Xebia Amsterdam, Wibautstraat 200/202, Amsterdam",
    "name": "Xebia Amsterdam",
    "lat": 52.36201,
    "lon": 4.90216
  },
  "amsterdam::Instapro Group (Amsterdam), Herengracht 469, Amsterdam": {
    "venue": "Instapro Group (Amsterdam), Herengracht 469, Amsterdam",
    "name": "Instapro Group (Amsterdam)",
    "lat": 52.33895,
    "lon": 4.87887
  },
  "amsterdam::Databricks Amsterdam": {
    "venue": "Databricks Amsterdam",
    "name": "Databricks Amsterdam",
    "lat": 52.35201,
    "lon": 4.91195
  },
  "amsterdam::Snowflake Amsterdam, Gustav Mahlerlaan 300-314, Amsterdam": {
    "venue": "Snowflake Amsterdam, Gustav Mahlerlaan 300-314, Amsterdam",
    "name": "Snowflake Amsterdam",
    "lat": 52.36574,
    "lon": 4.92985
  },
  "amsterdam::OrangeValley, De Corridor 27, Breukelen": {
    "venue": "OrangeValley, De Corridor 27, Breukelen",
    "name": "OrangeValley",
    "lat": 52.35845,
    "lon": 4.92475
  },
  "amsterdam::Vandebron, Grote Bickersstraat 2a, Amsterdam": {
    "venue": "Vandebron, Grote Bickersstraat 2a, Amsterdam",
    "name": "Vandebron",
    "lat": 52.34971,
    "lon": 4.91333
  },
  "amsterdam::Van Marwijk Kooystraat 15, Amsterdam": {
    "venue": "Van Marwijk Kooystraat 15, Amsterdam",
    "name": "Van Marwijk Kooystraat 15",
    "lat": 52.36207,
    "lon": 4.93039
  },
  "amsterdam::Wibautstraat 202, Amsterdam": {
    "venue": "Wibautstraat 202, Amsterdam",
    "name": "Wibautstraat 202",
    "lat": 52.35575,
    "lon": 4.87981
  },
  "analytics-engineering-belgium::De Hoorn, Sluisstraat 79, Leuven": {
    "venue": "De Hoorn, Sluisstraat 79, Leuven",
    "name": "De Hoorn",
    "lat": 50.82638,
    "lon": 4.35714
  },
  "analytics-engineering-belgium::OTA Insight, Gaston Crommenlaan 6, Gent": {
    "venue": "OTA Insight, Gaston Crommenlaan 6, Gent",
    "name": "OTA Insight",
    "lat": 50.83022,
    "lon": 4.35703
  },
  "analytics-engineering-belgium::Silversquare Delta, Av. Arnaud Fraiteur 15, Ixelles": {
    "venue": "Silversquare Delta, Av. Arnaud Fraiteur 15, Ixelles",
    "name": "Silversquare Delta",
    "lat": 50.86978,
    "lon": 4.35758
  },
  "analytics-engineering-belgium::Datashift NV, Oude Brusselsestraat 14, Mechelen": {
    "venue": "Datashift NV, Oude Brusselsestraat 14, Mechelen",
    "name": "Datashift NV",
    "lat": 50.83135,
    "lon": 4.3344
  },
  "analytics-engineering-belgium::Officenter Hasselt, Hendrik van Veldekesingel 150, Hasselt": {
    "venue": "Officenter Hasselt, Hendrik van Veldekesingel 150, Hasselt",
    "name": "Officenter Hasselt",
    "lat": 50.82967,
    "lon": 4.32612
  },
  "analytics-engineering-belgium::Dataroots, Tiensevest 132, Leuven": {
    "venue": "Dataroots, Tiensevest 132, Leuven",
    "name": "Dataroots",
    "lat": 50.87323,
    "lon": 4.35039
  },
  "analytics-engineering-belgium::DPG Media, Medialaan 1, Vilvoorde": {
    "venue": "DPG Media, Medialaan 1, Vilvoorde",
    "name": "DPG Media",
    "lat": 50.82354,
    "lon": 4.37867
  },
  "analytics-engineering-belgium::DataSense, Corda Campus, Kempische Steenweg 309, Hasselt": {
    "venue": "DataSense, Corda Campus, Kempische Steenweg 309, Hasselt",
    "name": "DataSense",
    "lat": 50.82792,
    "lon": 4.35168
  },
  "analytics-engineering-belgium::Lighthouse, Zuiderpoort, Gaston Crommenlaan 6, Ghent": {
    "venue": "Lighthouse, Zuiderpoort, Gaston Crommenlaan 6, Ghent",
    "name": "Lighthouse",
    "lat": 50.87872,
    "lon": 4.35465
  },
  "analytics-engineering-belgium::Dataminded, Vismarkt 17, Leuven": {
    "venue": "Dataminded, Vismarkt 17, Leuven",
    "name": "Dataminded",
    "lat": 50.84144,
    "lon": 4.33413
  },
  "analytics-engineering-belgium::Antwerp Port House, Zaha Hadidplein 1, Antwerp": {
    "venue": "Antwerp Port House, Zaha Hadidplein 1, Antwerp",
    "name": "Antwerp Port House",
    "lat": 50.82578,
    "lon": 4.35042
  },
  "analytics-engineering-belgium::IBA International Headquarters, Chemin du Cyclotron 3, Ottignies-Louvain-la-Neuve": {
    "venue": "IBA International Headquarters, Chemin du Cyclotron 3, Ottignies-Louvain-la-Neuve",
    "name": "IBA International Headquarters",
    "lat": 50.8529,
    "lon": 4.3524
  },
  "analytics-engineering-belgium::Telenet Hoofdkantoor, Liersesteenweg 4, Mechelen": {
    "venue": "Telenet Hoofdkantoor, Liersesteenweg 4, Mechelen",
    "name": "Telenet Hoofdkantoor",
    "lat": 50.86745,
    "lon": 4.35083
  },
  "analytics-engineering-belgium::BeCentral, Cantersteen 12, Brussels": {
    "venue": "BeCentral, Cantersteen 12, Brussels",
    "name": "BeCentral",
    "lat": 50.85805,
    "lon": 4.36113
  },
  "athens::Kaizen Campus, Neratziotissis 101, 15124, Marousi, Athens": {
    "venue": "Kaizen Campus, Neratziotissis 101, 15124, Marousi, Athens",
    "name": "Kaizen Campus",
    "lat": 38.00352,
    "lon": 23.75217
  },
  "athens::Agile Actors, Ethnikis Antistaseos 62A, Chalandri, Athens": {
    "venue": "Agile Actors, Ethnikis Antistaseos 62A, Chalandri, Athens",
    "name": "Agile Actors",
    "lat": 37.96132,
    "lon": 23.72082
  },
  "atlanta::7000 Central Pkwy, Sandy Springs, GA": {
    "venue": "7000 Central Pkwy, Sandy Springs, GA",
    "name": "7000 Central Pkwy",
    "lat": 33.74121,
    "lon": -84.39968
  },
  "atlanta::Mutation Brewing Company, 5825 Roswell Rd NE, Sandy Springs, GA": {
    "venue": "Mutation Brewing Company, 5825 Roswell Rd NE, Sandy Springs, GA",
    "name": "Mutation Brewing Company",
    "lat": 33.72105,
    "lon": -84.36196
  },
  "atlanta::NCR Voyix - Global Headquarters, 864 Spring St NW, Atlanta, GA": {
    "venue": "NCR Voyix - Global Headquarters, 864 Spring St NW, Atlanta, GA",
    "name": "NCR Voyix - Global Headquarters",
    "lat": 33.76369,
    "lon": -84.40184
  },
  "austin::Easy Tiger, 1501 E 7th St, Austin, TX": {
    "venue": "Easy Tiger, 1501 E 7th St, Austin, TX",
    "name": "Easy Tiger",
    "lat": 30.29356,
    "lon": -97.76993
  },
  "austin::Capital Factory, 701 Brazos St, Austin, TX": {
    "venue": "Capital Factory, 701 Brazos St, Austin, TX",
    "name": "Capital Factory",
    "lat": 30.26112,
    "lon": -97.75658
  },
  "austin::dbt Labs office - Austin, 522 Congress Ave. #700, Austin, TX": {
    "venue": "dbt Labs office - Austin, 522 Congress Ave. #700, Austin, TX",
    "name": "dbt Labs office - Austin",
    "lat": 30.29372,
    "lon": -97.73561
  },
  "austin::dbt Labs, 522 Congress Avenue, Suite 700, Austin, TX": {
    "venue": "dbt Labs, 522 Congress Avenue, Suite 700, Austin, TX",
    "name": "dbt Labs",
    "lat": 30.24143,
    "lon": -97.7268
  },
  "barcelona::Spaces 22 Arroba Mar, Carrer de la Marina, 16-18, Barcelona": {
    "venue": "Spaces 22 Arroba Mar, Carrer de la Marina, 16-18, Barcelona",
    "name": "Spaces 22 Arroba Mar",
    "lat": 41.41563,
    "lon": 2.17676
  },
  "barcelona::Ironhack Barcelona Tech bootcamps, C/ de Pamplona, 96, Barcelona": {
    "venue": "Ironhack Barcelona Tech bootcamps, C/ de Pamplona, 96, Barcelona",
    "name": "Ironhack Barcelona Tech bootcamps",
    "lat": 41.37388,
    "lon": 2.18505
  },
  "barcelona::Scopely - Sant Gervasi, Carrer de Folgueroles 17-25, Barcelona": {
    "venue": "Scopely - Sant Gervasi, Carrer de Folgueroles 17-25, Barcelona",
    "name": "Scopely - Sant Gervasi",
    "lat": 41.37292,
    "lon": 2.19551
  },
  "barcelona::Spaces 22 Arroba, C. de Pallars, 193, Barcelona": {
    "venue": "Spaces 22 Arroba, C. de Pallars, 193, Barcelona",
    "name": "Spaces 22 Arroba",
    "lat": 41.4168,
    "lon": 2.16276
  },
  "barcelona::Spaces - Barcelona, Plaza Universitat, Gran Via de les Corts Catalanes, 583, Barcelona": {
    "venue": "Spaces - Barcelona, Plaza Universitat, Gran Via de les Corts Catalanes, 583, Barcelona",
    "name": "Spaces - Barcelona",
    "lat": 41.35873,
    "lon": 2.14475
  },
  "barcelona::Spaces - Barcelona, Spaces 22 Arroba Mar, Carrer de la Marina, 16-18, Barcelona": {
    "venue": "Spaces - Barcelona, Spaces 22 Arroba Mar, Carrer de la Marina, 16-18, Barcelona",
    "name": "Spaces - Barcelona",
    "lat": 41.41173,
    "lon": 2.17093
  },
  "barcelona::Spaces - Plaza Universitat, Gran Via de les Corts Catalanes, 583, Barcelona": {
    "venue": "Spaces - Plaza Universitat, Gran Via de les Corts Catalanes, 583, Barcelona",
    "name": "Spaces - Plaza Universitat",
    "lat": 41.36458,
    "lon": 2.16189
  },
  "barcelona::Scopely Office, Carrer de Zamora, 70, Barcelona": {
    "venue": "Scopely Office, Carrer de Zamora, 70, Barcelona",
    "name": "Scopely Office",
    "lat": 41.37272,
    "lon": 2.14637
  },
  "barcelona::Pier01 / IFCO Digital Hub, Plaza de Pau Vila 1, Barcelona": {
    "venue": "Pier01 / IFCO Digital Hub, Plaza de Pau Vila 1, Barcelona",
    "name": "Pier01 / IFCO Digital Hub",
    "lat": 41.41228,
    "lon": 2.14238
  },
  "berlin::Jugendherberge Berlin Ostkreuz, Marktstraße 9-12, Berlin": {
    "venue": "Jugendherberge Berlin Ostkreuz, Marktstraße 9-12, Berlin",
    "name": "Jugendherberge Berlin Ostkreuz",
    "lat": 52.51997,
    "lon": 13.38519
  },
  "berlin::Contentful GmbH, Max-Urich-Straße 3, 13355 Berlin": {
    "venue": "Contentful GmbH, Max-Urich-Straße 3, 13355 Berlin",
    "name": "Contentful GmbH",
    "lat": 52.54489,
    "lon": 13.4087
  },
  "berlin::Vinted Office, Unter den Linden 14, 10117 Berlin": {
    "venue": "Vinted Office, Unter den Linden 14, 10117 Berlin",
    "name": "Vinted Office",
    "lat": 52.49519,
    "lon": 13.37552
  },
  "berlin::Umspannwerk Ampere, Sonnenburger Str. 73, 10437 Berlin, Germany": {
    "venue": "Umspannwerk Ampere, Sonnenburger Str. 73, 10437 Berlin, Germany",
    "name": "Umspannwerk Ampere",
    "lat": 52.51686,
    "lon": 13.40972
  },
  "berlin::Taxfix, Köpenicker Str. 122, 10179 Berlin, Germany": {
    "venue": "Taxfix, Köpenicker Str. 122, 10179 Berlin, Germany",
    "name": "Taxfix",
    "lat": 52.49174,
    "lon": 13.37978
  },
  "berlin::Neugelb Studios, Zeughofstraße 20, Berlin (Kreuzberg)": {
    "venue": "Neugelb Studios, Zeughofstraße 20, Berlin (Kreuzberg)",
    "name": "Neugelb Studios",
    "lat": 52.52624,
    "lon": 13.38683
  },
  "berlin::Enpal GmbH, Koppenstraße 8, 10243 Berlin, Germany (5th/6th floors)": {
    "venue": "Enpal GmbH, Koppenstraße 8, 10243 Berlin, Germany (5th/6th floors)",
    "name": "Enpal GmbH",
    "lat": 52.52719,
    "lon": 13.39799
  },
  "berlin::NEUGELB Studios GmbH, Zeughofstraße 20, Berlin": {
    "venue": "NEUGELB Studios GmbH, Zeughofstraße 20, Berlin",
    "name": "NEUGELB Studios GmbH",
    "lat": 52.51901,
    "lon": 13.39869
  },
  "berlin::Contentful, Ackerstraße 78, Berlin, BE": {
    "venue": "Contentful, Ackerstraße 78, Berlin, BE",
    "name": "Contentful",
    "lat": 52.49915,
    "lon": 13.40187
  },
  "berlin::DEPT®, Hagelberger Str. 53-54, Berlin, BE": {
    "venue": "DEPT®, Hagelberger Str. 53-54, Berlin, BE",
    "name": "DEPT®",
    "lat": 52.54667,
    "lon": 13.38041
  },
  "berlin::TIER Mobility SE, Eichhornstraße 3, Berlin, BE": {
    "venue": "TIER Mobility SE, Eichhornstraße 3, Berlin, BE",
    "name": "TIER Mobility SE",
    "lat": 52.51896,
    "lon": 13.41852
  },
  "berlin::Prater Beer Garden, Kastanienallee 7-9, Berlin, BE": {
    "venue": "Prater Beer Garden, Kastanienallee 7-9, Berlin, BE",
    "name": "Prater Beer Garden",
    "lat": 52.54131,
    "lon": 13.38215
  },
  "bogota::WeWork Usaquén, Carrera 7 #116-50, Bogotá": {
    "venue": "WeWork Usaquén, Carrera 7 #116-50, Bogotá",
    "name": "WeWork Usaquén",
    "lat": 4.71016,
    "lon": -74.06731
  },
  "boston::Convene, 201 Washington St, Boston, MA": {
    "venue": "Convene, 201 Washington St, Boston, MA",
    "name": "Convene",
    "lat": 42.36399,
    "lon": -71.03856
  },
  "boston::1 Lincoln St, Boston, MA": {
    "venue": "1 Lincoln St, Boston, MA",
    "name": "1 Lincoln St",
    "lat": 42.35639,
    "lon": -71.06367
  },
  "boston::Rapid7, 120 Causeway St, Boston, MA": {
    "venue": "Rapid7, 120 Causeway St, Boston, MA",
    "name": "Rapid7",
    "lat": 42.34514,
    "lon": -71.06186
  },
  "boston::2 Canal Park, Cambridge, MA": {
    "venue": "2 Canal Park, Cambridge, MA",
    "name": "2 Canal Park",
    "lat": 42.34572,
    "lon": -71.08164
  },
  "boston::125 Summer Street, Boston, MA": {
    "venue": "125 Summer Street, Boston, MA",
    "name": "125 Summer Street",
    "lat": 42.33137,
    "lon": -71.06337
  },
  "boston::Klaviyo, 125 Summer Street, Boston, MA": {
    "venue": "Klaviyo, 125 Summer Street, Boston, MA",
    "name": "Klaviyo",
    "lat": 42.35586,
    "lon": -71.06715
  },
  "boston::One Kenmore Square, Boston, MA": {
    "venue": "One Kenmore Square, Boston, MA",
    "name": "One Kenmore Square",
    "lat": 42.38166,
    "lon": -71.05215
  },
  "bratislava::The Spot, Bottova 2/A, Bratislava-Staré Mesto": {
    "venue": "The Spot, Bottova 2/A, Bratislava-Staré Mesto",
    "name": "The Spot",
    "lat": 48.1531,
    "lon": 17.08134
  },
  "bratislava::HubHub Twin City C, Mlynské nivy 16, Bratislava-Staré Mesto": {
    "venue": "HubHub Twin City C, Mlynské nivy 16, Bratislava-Staré Mesto",
    "name": "HubHub Twin City C",
    "lat": 48.13755,
    "lon": 17.13725
  },
  "bratislava::HB Reavis Twin City C, Mlynské Nivy 12, Bratislava": {
    "venue": "HB Reavis Twin City C, Mlynské Nivy 12, Bratislava",
    "name": "HB Reavis Twin City C",
    "lat": 48.12573,
    "lon": 17.10215
  },
  "bratislava::Apollo Business Center II, Block A, Prievozská 4, Bratislava": {
    "venue": "Apollo Business Center II, Block A, Prievozská 4, Bratislava",
    "name": "Apollo Business Center II",
    "lat": 48.13424,
    "lon": 17.0867
  },
  "brisbane::KeyData, 344 Queen St, Brisbane City": {
    "venue": "KeyData, 344 Queen St, Brisbane City",
    "name": "KeyData",
    "lat": -27.49133,
    "lon": 153.03831
  },
  "brisbane::Grand Central Hotel, 270 Ann St, Brisbane City": {
    "venue": "Grand Central Hotel, 270 Ann St, Brisbane City",
    "name": "Grand Central Hotel",
    "lat": -27.44868,
    "lon": 153.01915
  },
  "brisbane::Morgan's Financials, Level 29, Riverside Centre, 123 Eagle St, Brisbane": {
    "venue": "Morgan's Financials, Level 29, Riverside Centre, 123 Eagle St, Brisbane",
    "name": "Morgan's Financials",
    "lat": -27.46646,
    "lon": 153.0143
  },
  "brisbane::Vivianti Consulting, Level 23/300 Queen St, Brisbane": {
    "venue": "Vivianti Consulting, Level 23/300 Queen St, Brisbane",
    "name": "Vivianti Consulting",
    "lat": -27.47387,
    "lon": 153.01584
  },
  "budapest::Hubhub, 26 Király Street, Budapest": {
    "venue": "Hubhub, 26 Király Street, Budapest",
    "name": "Hubhub",
    "lat": 47.50738,
    "lon": 19.01113
  },
  "budapest::The Spot Budapest, Király utca 26, Budapest": {
    "venue": "The Spot Budapest, Király utca 26, Budapest",
    "name": "The Spot Budapest",
    "lat": 47.49454,
    "lon": 19.02302
  },
  "budapest::Create26, Király, 1061, Unit 26, Budapest": {
    "venue": "Create26, Király, 1061, Unit 26, Budapest",
    "name": "Create26",
    "lat": 47.50445,
    "lon": 19.04904
  },
  "buenos-aires::Mutt Data, Av. Sta. Fe 1752 PB B, Buenos Aires": {
    "venue": "Mutt Data, Av. Sta. Fe 1752 PB B, Buenos Aires",
    "name": "Mutt Data",
    "lat": -34.58229,
    "lon": -58.37567
  },
  "chicago::Convene, 333 N Green St, Chicago, IL": {
    "venue": "Convene, 333 N Green St, Chicago, IL",
    "name": "Convene",
    "lat": 41.86658,
    "lon": -87.60949
  },
  "chicago::150 N Michigan Ave, Chicago, IL": {
    "venue": "150 N Michigan Ave, Chicago, IL",
    "name": "150 N Michigan Ave",
    "lat": 41.89112,
    "lon": -87.61825
  },
  "chicago::55 E Monroe St suite 2950 c, Chicago, IL": {
    "venue": "55 E Monroe St suite 2950 c, Chicago, IL",
    "name": "55 E Monroe St suite 2950 c",
    "lat": 41.87914,
    "lon": -87.63583
  },
  "copenhagen::Møntergade 19, Copenhagen": {
    "venue": "Møntergade 19, Copenhagen",
    "name": "Møntergade 19",
    "lat": 55.70431,
    "lon": 12.59045
  },
  "copenhagen::Lederne, Vermlandsgade 65, Copenhagen": {
    "venue": "Lederne, Vermlandsgade 65, Copenhagen",
    "name": "Lederne",
    "lat": 55.7053,
    "lon": 12.53895
  },
  "copenhagen::Veo Technologies, Rovsingsgade 68, Copenhagen": {
    "venue": "Veo Technologies, Rovsingsgade 68, Copenhagen",
    "name": "Veo Technologies",
    "lat": 55.68388,
    "lon": 12.56584
  },
  "copenhagen::Lunar, Bredgade 43, Copenhagen": {
    "venue": "Lunar, Bredgade 43, Copenhagen",
    "name": "Lunar",
    "lat": 55.69265,
    "lon": 12.58849
  },
  "copenhagen::group.ONE, Kalvebod Brygge 24, Copenhagen": {
    "venue": "group.ONE, Kalvebod Brygge 24, Copenhagen",
    "name": "group.ONE",
    "lat": 55.68539,
    "lon": 12.55388
  },
  "copenhagen::Pleo HQ, Sortedam Dossering 7, Copenhagen": {
    "venue": "Pleo HQ, Sortedam Dossering 7, Copenhagen",
    "name": "Pleo HQ",
    "lat": 55.66803,
    "lon": 12.57405
  },
  "dallas::Venture X Dallas - Braniff Centre, 7701 Lemmon Ave Ste 260, Dallas, TX": {
    "venue": "Venture X Dallas - Braniff Centre, 7701 Lemmon Ave Ste 260, Dallas, TX",
    "name": "Venture X Dallas - Braniff Centre",
    "lat": 32.79178,
    "lon": -96.79785
  },
  "dallas::17746 Preston Rd Suite 200, Dallas, TX": {
    "venue": "17746 Preston Rd Suite 200, Dallas, TX",
    "name": "17746 Preston Rd Suite 200",
    "lat": 32.77181,
    "lon": -96.79692
  },
  "dc::Excella, 2300 Wilson Blvd Suite 600, Arlington, VA": {
    "venue": "Excella, 2300 Wilson Blvd Suite 600, Arlington, VA",
    "name": "Excella",
    "lat": 38.92215,
    "lon": -77.04656
  },
  "dc::Fundrise, 11 Dupont Cir NW, Washington, DC": {
    "venue": "Fundrise, 11 Dupont Cir NW, Washington, DC",
    "name": "Fundrise",
    "lat": 38.92418,
    "lon": -77.06138
  },
  "dc::NuAxis Innovations, 1919 Gallows Rd Suite 610, Vienna, VA": {
    "venue": "NuAxis Innovations, 1919 Gallows Rd Suite 610, Vienna, VA",
    "name": "NuAxis Innovations",
    "lat": 38.9018,
    "lon": -77.02594
  },
  "dc::Caboose Brewing Co & Tavern, 520 Mill St NE, Vienna, VA": {
    "venue": "Caboose Brewing Co & Tavern, 520 Mill St NE, Vienna, VA",
    "name": "Caboose Brewing Co & Tavern",
    "lat": 38.90604,
    "lon": -77.06666
  },
  "dc::NuAxis Innovations, 8605 Westwood Center Dr #300, Vienna, VA": {
    "venue": "NuAxis Innovations, 8605 Westwood Center Dr #300, Vienna, VA",
    "name": "NuAxis Innovations",
    "lat": 38.93527,
    "lon": -77.06079
  },
  "denver::Fivetran, 1401 Zuni St, Denver, CO": {
    "venue": "Fivetran, 1401 Zuni St, Denver, CO",
    "name": "Fivetran",
    "lat": 39.73707,
    "lon": -104.96663
  },
  "denver::Slalom, 1899 Wynkoop St, #800, Denver, CO": {
    "venue": "Slalom, 1899 Wynkoop St, #800, Denver, CO",
    "name": "Slalom",
    "lat": 39.75659,
    "lon": -104.98196
  },
  "dubai::Cander, 2205 AA1 Tower, Mazaya Business Avenue, Jumeirah Lake Towers, Dubai": {
    "venue": "Cander, 2205 AA1 Tower, Mazaya Business Avenue, Jumeirah Lake Towers, Dubai",
    "name": "Cander",
    "lat": 25.22949,
    "lon": 55.29454
  },
  "dubai::Cander Group DMCC, Jumeirah Lake Towers, Dubai": {
    "venue": "Cander Group DMCC, Jumeirah Lake Towers, Dubai",
    "name": "Cander Group DMCC",
    "lat": 25.17846,
    "lon": 55.2766
  },
  "dubai::The Black Sheep, Pullman Hotel, Dubai": {
    "venue": "The Black Sheep, Pullman Hotel, Dubai",
    "name": "The Black Sheep",
    "lat": 25.17505,
    "lon": 55.30031
  },
  "dublin::dbt Labs office, 57-59 Sir John Rogerson's Quay, Dublin 2": {
    "venue": "dbt Labs office, 57-59 Sir John Rogerson's Quay, Dublin 2",
    "name": "dbt Labs office",
    "lat": 53.37081,
    "lon": -6.24237
  },
  "dublin::dbt Labs Ireland, 4th Floor, Bloodstone Building, Sir John Rogerson's Quay, Dublin": {
    "venue": "dbt Labs Ireland, 4th Floor, Bloodstone Building, Sir John Rogerson's Quay, Dublin",
    "name": "dbt Labs Ireland",
    "lat": 53.33039,
    "lon": -6.25752
  },
  "florianopolis::ACATE, Rodovia SC 401, Florianópolis, SC": {
    "venue": "ACATE, Rodovia SC 401, Florianópolis, SC",
    "name": "ACATE",
    "lat": -27.58776,
    "lon": -48.55409
  },
  "florianopolis::Lemonadde Coworking + Offices, Rod. Admar Gonzaga, 440, Florianópolis, SC": {
    "venue": "Lemonadde Coworking + Offices, Rod. Admar Gonzaga, 440, Florianópolis, SC",
    "name": "Lemonadde Coworking + Offices",
    "lat": -27.62233,
    "lon": -48.54848
  },
  "florianopolis::ACATE | Centro de Inovação, Florianópolis, SC": {
    "venue": "ACATE | Centro de Inovação, Florianópolis, SC",
    "name": "ACATE | Centro de Inovação",
    "lat": -27.59013,
    "lon": -48.54982
  },
  "florianopolis::Wooden Tap Beer, Travessa Albertina Ganzo, 33, Florianópolis, SC": {
    "venue": "Wooden Tap Beer, Travessa Albertina Ganzo, 33, Florianópolis, SC",
    "name": "Wooden Tap Beer",
    "lat": -27.60287,
    "lon": -48.55656
  },
  "florianopolis::Auditório ACATE, SC401, km4, Florianópolis": {
    "venue": "Auditório ACATE, SC401, km4, Florianópolis",
    "name": "Auditório ACATE",
    "lat": -27.59745,
    "lon": -48.53905
  },
  "halifax::CoWork Halifax, 6156 Quinpool Rd, Halifax, NS": {
    "venue": "CoWork Halifax, 6156 Quinpool Rd, Halifax, NS",
    "name": "CoWork Halifax",
    "lat": 44.66665,
    "lon": -63.59054
  },
  "helsinki::Fredrikinkatu 51, Helsinki": {
    "venue": "Fredrikinkatu 51, Helsinki",
    "name": "Fredrikinkatu 51",
    "lat": 60.15142,
    "lon": 24.95265
  },
  "helsinki::Smartly.io Event Space, Elielinaukio 2, Helsinki": {
    "venue": "Smartly.io Event Space, Elielinaukio 2, Helsinki",
    "name": "Smartly.io Event Space",
    "lat": 60.17396,
    "lon": 24.92525
  },
  "helsinki::Dylan Marmoripiha, Keskuskatu 3, Helsinki": {
    "venue": "Dylan Marmoripiha, Keskuskatu 3, Helsinki",
    "name": "Dylan Marmoripiha",
    "lat": 60.14126,
    "lon": 24.94361
  },
  "ho-chi-minh-city::Dreamplex Ngo Quang Huy, 42 Ngô Quang Huy, District 2, Ho Chi Minh City": {
    "venue": "Dreamplex Ngo Quang Huy, 42 Ngô Quang Huy, District 2, Ho Chi Minh City",
    "name": "Dreamplex Ngo Quang Huy",
    "lat": 10.83485,
    "lon": 106.65488
  },
  "ho-chi-minh-city::3 Đường số 46, District 2, Ho Chi Minh City": {
    "venue": "3 Đường số 46, District 2, Ho Chi Minh City",
    "name": "3 Đường số 46",
    "lat": 10.81898,
    "lon": 106.6407
  },
  "ho-chi-minh-city::Chotot Office, UOA Tower, District 7, Ho Chi Minh City": {
    "venue": "Chotot Office, UOA Tower, District 7, Ho Chi Minh City",
    "name": "Chotot Office",
    "lat": 10.85267,
    "lon": 106.64171
  },
  "ho-chi-minh-city::DHC Vietnam, 15 Phạm Hùng, Hà Nội": {
    "venue": "DHC Vietnam, 15 Phạm Hùng, Hà Nội",
    "name": "DHC Vietnam",
    "lat": 10.83628,
    "lon": 106.64393
  },
  "ho-chi-minh-city::THINK Training Space, 116 Đ. Nguyễn Văn Thủ, District 1, Ho Chi Minh City": {
    "venue": "THINK Training Space, 116 Đ. Nguyễn Văn Thủ, District 1, Ho Chi Minh City",
    "name": "THINK Training Space",
    "lat": 10.82099,
    "lon": 106.64571
  },
  "ho-chi-minh-city::Holistics Vietnam office, 457 Nguyễn Đình Chiểu, District 3, Ho Chi Minh City": {
    "venue": "Holistics Vietnam office, 457 Nguyễn Đình Chiểu, District 3, Ho Chi Minh City",
    "name": "Holistics Vietnam office",
    "lat": 10.83738,
    "lon": 106.63875
  },
  "ho-chi-minh-city::Family Garden 2, 28 Đ. Thảo Điền, District 2, Ho Chi Minh City": {
    "venue": "Family Garden 2, 28 Đ. Thảo Điền, District 2, Ho Chi Minh City",
    "name": "Family Garden 2",
    "lat": 10.81777,
    "lon": 106.65266
  },
  "ho-chi-minh-city::C-Space Coworking Office, 62 Võ Văn Tần, District 3, Ho Chi Minh City": {
    "venue": "C-Space Coworking Office, 62 Võ Văn Tần, District 3, Ho Chi Minh City",
    "name": "C-Space Coworking Office",
    "lat": 10.83979,
    "lon": 106.63373
  },
  "ho-chi-minh-city::Foundry AI Academy, Binh Thanh District, Ho Chi Minh City": {
    "venue": "Foundry AI Academy, Binh Thanh District, Ho Chi Minh City",
    "name": "Foundry AI Academy",
    "lat": 10.84543,
    "lon": 106.62483
  },
  "houston::Karbach Brewing Co., 2032 Karbach St, Houston, TX": {
    "venue": "Karbach Brewing Co., 2032 Karbach St, Houston, TX",
    "name": "Karbach Brewing Co.",
    "lat": 29.74112,
    "lon": -95.3431
  },
  "houston::Buffalo Bayou Brewing Company, 2101 Summer St, Houston, TX": {
    "venue": "Buffalo Bayou Brewing Company, 2101 Summer St, Houston, TX",
    "name": "Buffalo Bayou Brewing Company",
    "lat": 29.7624,
    "lon": -95.34926
  },
  "houston::Axelrad Beer Garden, 1517 Alabama Street, Houston, TX": {
    "venue": "Axelrad Beer Garden, 1517 Alabama Street, Houston, TX",
    "name": "Axelrad Beer Garden",
    "lat": 29.75505,
    "lon": -95.35378
  },
  "lagos::(DSN) Data Scientists Network / Data Science Nigeria AI Hub, 33 Queen St, Lagos": {
    "venue": "(DSN) Data Scientists Network / Data Science Nigeria AI Hub, 33 Queen St, Lagos",
    "name": "(DSN) Data Scientists Network / Data Science Nigeria AI Hub",
    "lat": 6.506,
    "lon": 3.37395
  },
  "lagos::Cafe One by Sterling, Commercial Ave, Lagos": {
    "venue": "Cafe One by Sterling, Commercial Ave, Lagos",
    "name": "Cafe One by Sterling",
    "lat": 6.51905,
    "lon": 3.37793
  },
  "lagos::The Nest Innovation Hub, 1a Hughes Avenue, Yaba, Lagos": {
    "venue": "The Nest Innovation Hub, 1a Hughes Avenue, Yaba, Lagos",
    "name": "The Nest Innovation Hub",
    "lat": 6.4977,
    "lon": 3.37552
  },
  "lagos::Bridge by Obsidian, 6 University Road, Onike, Yaba, Lagos": {
    "venue": "Bridge by Obsidian, 6 University Road, Onike, Yaba, Lagos",
    "name": "Bridge by Obsidian",
    "lat": 6.55193,
    "lon": 3.35756
  },
  "lagos::The Nest Innovation Technology Park, 1a Hughes Avenue, Yaba, Lagos": {
    "venue": "The Nest Innovation Technology Park, 1a Hughes Avenue, Yaba, Lagos",
    "name": "The Nest Innovation Technology Park",
    "lat": 6.5022,
    "lon": 3.35696
  },
  "london::The Information Lab, 25 Watling St, City of London, London EC4M 9BR": {
    "venue": "The Information Lab, 25 Watling St, City of London, London EC4M 9BR",
    "name": "The Information Lab",
    "lat": 51.5275,
    "lon": -0.14895
  },
  "london::The Information Lab, 25 Watling St, London EC4M 9BR": {
    "venue": "The Information Lab, 25 Watling St, London EC4M 9BR",
    "name": "The Information Lab",
    "lat": 51.51372,
    "lon": -0.1438
  },
  "london::Snowflake Office, One Crown Place, London, EC2A 4EF": {
    "venue": "Snowflake Office, One Crown Place, London, EC2A 4EF",
    "name": "Snowflake Office",
    "lat": 51.51456,
    "lon": -0.14252
  },
  "london::The Anthologist Bar & Club, 58 Gresham St, London EC2V 7BB": {
    "venue": "The Anthologist Bar & Club, 58 Gresham St, London EC2V 7BB",
    "name": "The Anthologist Bar & Club",
    "lat": 51.5083,
    "lon": -0.13632
  },
  "london::Datatonic, 1 Canada Square, London": {
    "venue": "Datatonic, 1 Canada Square, London",
    "name": "Datatonic",
    "lat": 51.52602,
    "lon": -0.10442
  },
  "london::Level39, Canary Wharf, London": {
    "venue": "Level39, Canary Wharf, London",
    "name": "Level39",
    "lat": 51.52694,
    "lon": -0.0978
  },
  "london::Receipt Bank, 99 Clifton Street, London": {
    "venue": "Receipt Bank, 99 Clifton Street, London",
    "name": "Receipt Bank",
    "lat": 51.47973,
    "lon": -0.12548
  },
  "london::RVU, 5 Copper Row, London": {
    "venue": "RVU, 5 Copper Row, London",
    "name": "RVU",
    "lat": 51.53689,
    "lon": -0.13014
  },
  "london::Simply Business, 99 Gresham Street, London": {
    "venue": "Simply Business, 99 Gresham Street, London",
    "name": "Simply Business",
    "lat": 51.4908,
    "lon": -0.10125
  },
  "london::Growth Street, 22-30 Dukes Place, London": {
    "venue": "Growth Street, 22-30 Dukes Place, London",
    "name": "Growth Street",
    "lat": 51.51398,
    "lon": -0.1547
  },
  "los-angeles::FanDuel, 6701 Center Dr W, Los Angeles, CA": {
    "venue": "FanDuel, 6701 Center Dr W, Los Angeles, CA",
    "name": "FanDuel",
    "lat": 34.04746,
    "lon": -118.26905
  },
  "los-angeles::11520 W Pico Blvd, Los Angeles, CA": {
    "venue": "11520 W Pico Blvd, Los Angeles, CA",
    "name": "11520 W Pico Blvd",
    "lat": 34.02971,
    "lon": -118.21454
  },
  "madrid::Utopicus Paseo de la Habana, Paseo de la Habana 9-11, Madrid": {
    "venue": "Utopicus Paseo de la Habana, Paseo de la Habana 9-11, Madrid",
    "name": "Utopicus Paseo de la Habana",
    "lat": 40.41096,
    "lon": -3.70779
  },
  "madrid::Utopicus Habana, P.º de La Habana 9-11, Madrid": {
    "venue": "Utopicus Habana, P.º de La Habana 9-11, Madrid",
    "name": "Utopicus Habana",
    "lat": 40.39406,
    "lon": -3.72451
  },
  "madrid::Utopicus Principe de Vergara, C. del Príncipe de Vergara 112, Madrid": {
    "venue": "Utopicus Principe de Vergara, C. del Príncipe de Vergara 112, Madrid",
    "name": "Utopicus Principe de Vergara",
    "lat": 40.4105,
    "lon": -3.72585
  },
  "madrid::P.º de La Habana 9-11, Madrid": {
    "venue": "P.º de La Habana 9-11, Madrid",
    "name": "P.º de La Habana 9-11",
    "lat": 40.42776,
    "lon": -3.72738
  },
  "manila::Good Neighbor, Unit 9, Ground Floor, Verve One, Taguig, Metro Manila": {
    "venue": "Good Neighbor, Unit 9, Ground Floor, Verve One, Taguig, Metro Manila",
    "name": "Good Neighbor",
    "lat": 14.58853,
    "lon": 120.98164
  },
  "marseille::Le Mangrove, 154 Rue de Rome, Marseille": {
    "venue": "Le Mangrove, 154 Rue de Rome, Marseille",
    "name": "Le Mangrove",
    "lat": 43.29917,
    "lon": 5.37974
  },
  "medellin::WeWork Los Balsos, Carrera 42 #5 Sur-145, Medellín": {
    "venue": "WeWork Los Balsos, Carrera 42 #5 Sur-145, Medellín",
    "name": "WeWork Los Balsos",
    "lat": 6.26762,
    "lon": -75.57666
  },
  "melbourne::Mantel Group, Level 2, 452 Flinders St, Melbourne VIC": {
    "venue": "Mantel Group, Level 2, 452 Flinders St, Melbourne VIC",
    "name": "Mantel Group",
    "lat": -37.83917,
    "lon": 144.9826
  },
  "milan::Data Reply, Via Robert Koch 1/4, Milano": {
    "venue": "Data Reply, Via Robert Koch 1/4, Milano",
    "name": "Data Reply",
    "lat": 45.47407,
    "lon": 9.19345
  },
  "minneapolis::Sky Lounge @ North Loop Green 360, 360 N 5th St, Minneapolis, MN": {
    "venue": "Sky Lounge @ North Loop Green 360, 360 N 5th St, Minneapolis, MN",
    "name": "Sky Lounge @ North Loop Green 360",
    "lat": 44.96644,
    "lon": -93.24528
  },
  "minneapolis::Improving, 1515 Central Ave NE Suite 100, Minneapolis, MN": {
    "venue": "Improving, 1515 Central Ave NE Suite 100, Minneapolis, MN",
    "name": "Improving",
    "lat": 44.95203,
    "lon": -93.28588
  },
  "minneapolis::FINNEGANS Brew Co., 817 5th Ave S, Minneapolis, MN": {
    "venue": "FINNEGANS Brew Co., 817 5th Ave S, Minneapolis, MN",
    "name": "FINNEGANS Brew Co.",
    "lat": 44.99973,
    "lon": -93.25172
  },
  "montreal::Solution BI Canada, 4200 Boul. Saint-Laurent Suite 425, Montréal, QC": {
    "venue": "Solution BI Canada, 4200 Boul. Saint-Laurent Suite 425, Montréal, QC",
    "name": "Solution BI Canada",
    "lat": 45.48323,
    "lon": -73.54939
  },
  "montreal::Dialogue, 455 Rue Sainte-Hélène Suite 200, Montréal, QC": {
    "venue": "Dialogue, 455 Rue Sainte-Hélène Suite 200, Montréal, QC",
    "name": "Dialogue",
    "lat": 45.52614,
    "lon": -73.57973
  },
  "montreal::Unito, 1265 Rue Berri 7th floor, Montreal, QC": {
    "venue": "Unito, 1265 Rue Berri 7th floor, Montreal, QC",
    "name": "Unito",
    "lat": 45.52748,
    "lon": -73.55308
  },
  "munich::Synabi Business Solutions GmbH, Oskar-Schlemmer-Straße 13, München": {
    "venue": "Synabi Business Solutions GmbH, Oskar-Schlemmer-Straße 13, München",
    "name": "Synabi Business Solutions GmbH",
    "lat": 48.14607,
    "lon": 11.56042
  },
  "munich::Daiichi Sankyo, Zielstattstraße 48, Munich": {
    "venue": "Daiichi Sankyo, Zielstattstraße 48, Munich",
    "name": "Daiichi Sankyo",
    "lat": 48.14182,
    "lon": 11.57676
  },
  "norther-germany::HDI Versicherung AG, HDI-Platz 1, Hanover": {
    "venue": "HDI Versicherung AG, HDI-Platz 1, Hanover",
    "name": "HDI Versicherung AG",
    "lat": 52.36832,
    "lon": 9.71326
  },
  "norther-germany::House of New Work - by Blackboat, Königstraße 28, Hamburg": {
    "venue": "House of New Work - by Blackboat, Königstraße 28, Hamburg",
    "name": "House of New Work - by Blackboat",
    "lat": 52.40163,
    "lon": 9.72335
  },
  "nyc::Datadog, 620 8th Ave, 47th floor, New York, NY 10018": {
    "venue": "Datadog, 620 8th Ave, 47th floor, New York, NY 10018",
    "name": "Datadog",
    "lat": 40.71892,
    "lon": -73.97856
  },
  "nyc::Datadog, 620 8th Ave, 45th floor, New York, NY 10018": {
    "venue": "Datadog, 620 8th Ave, 45th floor, New York, NY 10018",
    "name": "Datadog",
    "lat": 40.72173,
    "lon": -74.0186
  },
  "nyc::DoubleVerify Headquarters, 28 Crosby Street, floor 6, New York, NY 10013": {
    "venue": "DoubleVerify Headquarters, 28 Crosby Street, floor 6, New York, NY 10013",
    "name": "DoubleVerify Headquarters",
    "lat": 40.7105,
    "lon": -74.00134
  },
  "nyc::Datadog, 620 8th Ave, 45th floor, New York, NY": {
    "venue": "Datadog, 620 8th Ave, 45th floor, New York, NY",
    "name": "Datadog",
    "lat": 40.71591,
    "lon": -73.97755
  },
  "nyc::Sixth Floor Loft (2nd floor), 873 Broadway, New York, NY": {
    "venue": "Sixth Floor Loft (2nd floor), 873 Broadway, New York, NY",
    "name": "Sixth Floor Loft (2nd floor)",
    "lat": 40.72547,
    "lon": -73.98292
  },
  "nyc::Materialize, 436 Lafayette St floor 6, New York, NY 10003": {
    "venue": "Materialize, 436 Lafayette St floor 6, New York, NY 10003",
    "name": "Materialize",
    "lat": 40.71894,
    "lon": -74.01631
  },
  "nyc::GameChanger, 124 E 14th St 17th floor, New York, NY": {
    "venue": "GameChanger, 124 E 14th St 17th floor, New York, NY",
    "name": "GameChanger",
    "lat": 40.71057,
    "lon": -74.03276
  },
  "nyc::Sigma Computing, 124 E 14th St 9th floor, New York, NY": {
    "venue": "Sigma Computing, 124 E 14th St 9th floor, New York, NY",
    "name": "Sigma Computing",
    "lat": 40.72063,
    "lon": -74.02234
  },
  "nyc::Fanduel, New York, NY (exact address released day-of)": {
    "venue": "Fanduel, New York, NY (exact address released day-of)",
    "name": "Fanduel",
    "lat": 40.74029,
    "lon": -73.98167
  },
  "nyc::FanDuel office, Chelsea-Flatiron area, New York, NY": {
    "venue": "FanDuel office, Chelsea-Flatiron area, New York, NY",
    "name": "FanDuel office",
    "lat": 40.69956,
    "lon": -74.0117
  },
  "nyc::Convene, 530 5th Ave floor 9, New York, NY": {
    "venue": "Convene, 530 5th Ave floor 9, New York, NY",
    "name": "Convene",
    "lat": 40.73535,
    "lon": -74.00934
  },
  "nyc::Bowery Farming HQ, 151 W 26th St 12th floor, New York, NY": {
    "venue": "Bowery Farming HQ, 151 W 26th St 12th floor, New York, NY",
    "name": "Bowery Farming HQ",
    "lat": 40.69963,
    "lon": -73.99607
  },
  "nyc::Warby Parker HQ and Showroom, 233 Spring St 6th Floor E, New York, NY": {
    "venue": "Warby Parker HQ and Showroom, 233 Spring St 6th Floor E, New York, NY",
    "name": "Warby Parker HQ and Showroom",
    "lat": 40.71056,
    "lon": -74.0001
  },
  "nyc::230 Park Ave S, New York, NY": {
    "venue": "230 Park Ave S, New York, NY",
    "name": "230 Park Ave S",
    "lat": 40.71857,
    "lon": -74.03425
  },
  "oslo-dbt-group::Sundtkvartalet, Lakkegata 53, Oslo": {
    "venue": "Sundtkvartalet, Lakkegata 53, Oslo",
    "name": "Sundtkvartalet",
    "lat": 59.93303,
    "lon": 10.75012
  },
  "oslo-dbt-group::Rebel, Universitetsgata 2, Oslo": {
    "venue": "Rebel, Universitetsgata 2, Oslo",
    "name": "Rebel",
    "lat": 59.89123,
    "lon": 10.7397
  },
  "oslo-dbt-group::Telenor, Snarøyveien 30, Fornebu, Oslo": {
    "venue": "Telenor, Snarøyveien 30, Fornebu, Oslo",
    "name": "Telenor",
    "lat": 59.89577,
    "lon": 10.74918
  },
  "oslo-dbt-group::Akersgata 34, Oslo": {
    "venue": "Akersgata 34, Oslo",
    "name": "Akersgata 34",
    "lat": 59.9116,
    "lon": 10.76244
  },
  "oslo-dbt-group::Computashuset, Akersgata 35, Oslo": {
    "venue": "Computashuset, Akersgata 35, Oslo",
    "name": "Computashuset",
    "lat": 59.91317,
    "lon": 10.77865
  },
  "paris::Deskeo, 32 Rue René Boulanger, Paris": {
    "venue": "Deskeo, 32 Rue René Boulanger, Paris",
    "name": "Deskeo",
    "lat": 48.82835,
    "lon": 2.3694
  },
  "paris::Coolandworkers, 2 rue de Dahomey, Paris": {
    "venue": "Coolandworkers, 2 rue de Dahomey, Paris",
    "name": "Coolandworkers",
    "lat": 48.88501,
    "lon": 2.36311
  },
  "paris::Founders Café, STATION F, Paris": {
    "venue": "Founders Café, STATION F, Paris",
    "name": "Founders Café",
    "lat": 48.84616,
    "lon": 2.33453
  },
  "paris::Payfit, 1 Rue de Saint-Pétersbourg, Paris": {
    "venue": "Payfit, 1 Rue de Saint-Pétersbourg, Paris",
    "name": "Payfit",
    "lat": 48.84823,
    "lon": 2.35572
  },
  "paris::Stuart offices, 43-45 Avenue de Clichy, Paris": {
    "venue": "Stuart offices, 43-45 Avenue de Clichy, Paris",
    "name": "Stuart offices",
    "lat": 48.86459,
    "lon": 2.32936
  },
  "paris::The Red Balloon, 51 Rue Notre Dame de Nazareth, Paris": {
    "venue": "The Red Balloon, 51 Rue Notre Dame de Nazareth, Paris",
    "name": "The Red Balloon",
    "lat": 48.82916,
    "lon": 2.36237
  },
  "philadelphia::dbt Labs office, 915 Spring Garden St #500, Philadelphia, PA": {
    "venue": "dbt Labs office, 915 Spring Garden St #500, Philadelphia, PA",
    "name": "dbt Labs office",
    "lat": 39.97469,
    "lon": -75.13955
  },
  "philadelphia::Slalom Consulting, 100 N 18th St Suite 2000, Philadelphia, PA": {
    "venue": "Slalom Consulting, 100 N 18th St Suite 2000, Philadelphia, PA",
    "name": "Slalom Consulting",
    "lat": 39.96739,
    "lon": -75.19458
  },
  "phoenix::Slalom Consulting, 7150 E Camelback Rd #200, Scottsdale, AZ": {
    "venue": "Slalom Consulting, 7150 E Camelback Rd #200, Scottsdale, AZ",
    "name": "Slalom Consulting",
    "lat": 33.45573,
    "lon": -112.04683
  },
  "portland::InterWorks @ Kiln, 1120 Southeast Madison Street, Portland, OR": {
    "venue": "InterWorks @ Kiln, 1120 Southeast Madison Street, Portland, OR",
    "name": "InterWorks @ Kiln",
    "lat": 45.54417,
    "lon": -122.68238
  },
  "prague::Philip Morris, Karlovo nám. 2097, Prague": {
    "venue": "Philip Morris, Karlovo nám. 2097, Prague",
    "name": "Philip Morris",
    "lat": 50.09699,
    "lon": 14.40781
  },
  "prague::MSD IT, FIVE Building, Na Valentince 3336/4, Prague": {
    "venue": "MSD IT, FIVE Building, Na Valentince 3336/4, Prague",
    "name": "MSD IT",
    "lat": 50.09682,
    "lon": 14.41426
  },
  "prague::STRV, Rohanské nábřeží 678/23, Prague": {
    "venue": "STRV, Rohanské nábřeží 678/23, Prague",
    "name": "STRV",
    "lat": 50.09982,
    "lon": 14.42755
  },
  "raleigh-d::Boxyard RTP, 842-898 Park Offices Dr, Morrisville, NC": {
    "venue": "Boxyard RTP, 842-898 Park Offices Dr, Morrisville, NC",
    "name": "Boxyard RTP",
    "lat": 35.77999,
    "lon": -78.63434
  },
  "rhein-ruhr::taod Consulting GmbH, Oskar-Jäger-Str. 173, K4, Cologne": {
    "venue": "taod Consulting GmbH, Oskar-Jäger-Str. 173, K4, Cologne",
    "name": "taod Consulting GmbH",
    "lat": 50.91405,
    "lon": 6.9725
  },
  "rhein-ruhr::adesso SE, Agrippinawerft 26, Köln": {
    "venue": "adesso SE, Agrippinawerft 26, Köln",
    "name": "adesso SE",
    "lat": 50.95814,
    "lon": 6.94805
  },
  "riyadh::Grand Plaza Dhabab Hotel, Riyadh": {
    "venue": "Grand Plaza Dhabab Hotel, Riyadh",
    "name": "Grand Plaza Dhabab Hotel",
    "lat": 24.68464,
    "lon": 46.69567
  },
  "san-francisco::The Academy, 2166 Market Street, San Francisco, CA": {
    "venue": "The Academy, 2166 Market Street, San Francisco, CA",
    "name": "The Academy",
    "lat": 37.79901,
    "lon": -122.43754
  },
  "san-francisco::Trellis Coworking, Events, Cafe & Bar, 981 Mission St, San Francisco, CA": {
    "venue": "Trellis Coworking, Events, Cafe & Bar, 981 Mission St, San Francisco, CA",
    "name": "Trellis Coworking",
    "lat": 37.75687,
    "lon": -122.40234
  },
  "san-francisco::dbt Labs, 650 California St suite 1501, San Francisco, CA": {
    "venue": "dbt Labs, 650 California St suite 1501, San Francisco, CA",
    "name": "dbt Labs",
    "lat": 37.7643,
    "lon": -122.44583
  },
  "san-francisco::Thoughtspot, 444 Castro St suite 1000, Mountain View, CA": {
    "venue": "Thoughtspot, 444 Castro St suite 1000, Mountain View, CA",
    "name": "Thoughtspot",
    "lat": 37.78921,
    "lon": -122.41488
  },
  "san-francisco::dbt Labs, 650 California St, San Francisco, CA": {
    "venue": "dbt Labs, 650 California St, San Francisco, CA",
    "name": "dbt Labs",
    "lat": 37.80084,
    "lon": -122.40397
  },
  "san-francisco::Envoy, 410 Townsend St 4th floor, San Francisco, CA": {
    "venue": "Envoy, 410 Townsend St 4th floor, San Francisco, CA",
    "name": "Envoy",
    "lat": 37.80133,
    "lon": -122.44815
  },
  "san-francisco::Grove Collaborative, 1301 Sansome St, San Francisco, CA": {
    "venue": "Grove Collaborative, 1301 Sansome St, San Francisco, CA",
    "name": "Grove Collaborative",
    "lat": 37.7878,
    "lon": -122.42146
  },
  "sao-paulo::ESPM São Paulo, R. Joaquim Távora, 1240, São Paulo": {
    "venue": "ESPM São Paulo, R. Joaquim Távora, 1240, São Paulo",
    "name": "ESPM São Paulo",
    "lat": -23.52211,
    "lon": -46.65096
  },
  "sao-paulo::Oracle do Brasil, Rua Dr Jose Aureo Bustamante 455, São Paulo": {
    "venue": "Oracle do Brasil, Rua Dr Jose Aureo Bustamante 455, São Paulo",
    "name": "Oracle do Brasil",
    "lat": -23.56197,
    "lon": -46.61723
  },
  "sao-paulo::FIAP - Paulista, 1106 Avenida Paulista, São Paulo": {
    "venue": "FIAP - Paulista, 1106 Avenida Paulista, São Paulo",
    "name": "FIAP - Paulista",
    "lat": -23.55165,
    "lon": -46.64697
  },
  "sao-paulo::FIAP, Av. Paulista, 1106, São Paulo": {
    "venue": "FIAP, Av. Paulista, 1106, São Paulo",
    "name": "FIAP",
    "lat": -23.54653,
    "lon": -46.61027
  },
  "sao-paulo::FIA Business School, Av. Dra. Ruth Cardoso, 7221, São Paulo": {
    "venue": "FIA Business School, Av. Dra. Ruth Cardoso, 7221, São Paulo",
    "name": "FIA Business School",
    "lat": -23.5224,
    "lon": -46.62513
  },
  "seattle::Docusign Tower, 999 3rd Ave #1000, Seattle, WA": {
    "venue": "Docusign Tower, 999 3rd Ave #1000, Seattle, WA",
    "name": "Docusign Tower",
    "lat": 47.6305,
    "lon": -122.32638
  },
  "seattle::Madrona Ventures, 999 Third Avenue, 33rd floor, Seattle, WA": {
    "venue": "Madrona Ventures, 999 Third Avenue, 33rd floor, Seattle, WA",
    "name": "Madrona Ventures",
    "lat": 47.62644,
    "lon": -122.33347
  },
  "seattle::WeWork Holyoke Building, 107 Spring St, Seattle, WA": {
    "venue": "WeWork Holyoke Building, 107 Spring St, Seattle, WA",
    "name": "WeWork Holyoke Building",
    "lat": 47.62483,
    "lon": -122.35061
  },
  "seattle::Foundations, 1605 Boylston Ave, Seattle, WA": {
    "venue": "Foundations, 1605 Boylston Ave, Seattle, WA",
    "name": "Foundations",
    "lat": 47.61652,
    "lon": -122.35431
  },
  "seattle::999 3rd Ave, Seattle, WA (Docusign Tower)": {
    "venue": "999 3rd Ave, Seattle, WA (Docusign Tower)",
    "name": "999 3rd Ave",
    "lat": 47.61346,
    "lon": -122.3281
  },
  "seattle::1425 4th Ave, Seattle, WA": {
    "venue": "1425 4th Ave, Seattle, WA",
    "name": "1425 4th Ave",
    "lat": 47.59005,
    "lon": -122.31513
  },
  "seattle::2107 Elliott Ave #302, Seattle, WA": {
    "venue": "2107 Elliott Ave #302, Seattle, WA",
    "name": "2107 Elliott Ave #302",
    "lat": 47.57657,
    "lon": -122.31628
  },
  "seoul::MARU360, B1, 172 Yeoksam-ro, Gangnam-gu, Seoul": {
    "venue": "MARU360, B1, 172 Yeoksam-ro, Gangnam-gu, Seoul",
    "name": "MARU360",
    "lat": 37.58659,
    "lon": 126.96536
  },
  "seoul::Snowflake Korea Office, 134 Teheran-ro, Gangnam-gu, Seoul": {
    "venue": "Snowflake Korea Office, 134 Teheran-ro, Gangnam-gu, Seoul",
    "name": "Snowflake Korea Office",
    "lat": 37.55615,
    "lon": 126.9547
  },
  "seoul::Berry Space, 28 Bongeunsa-ro 16-gil, Gangnam-gu, Seoul": {
    "venue": "Berry Space, 28 Bongeunsa-ro 16-gil, Gangnam-gu, Seoul",
    "name": "Berry Space",
    "lat": 37.5465,
    "lon": 126.97526
  },
  "seoul::Jidining Company, 629-1 Yeoksam-dong, Gangnam-gu, Seoul": {
    "venue": "Jidining Company, 629-1 Yeoksam-dong, Gangnam-gu, Seoul",
    "name": "Jidining Company",
    "lat": 37.55935,
    "lon": 127.0072
  },
  "seoul::OrangePlanet, 4th Floor, Gangnam-gu, Seoul": {
    "venue": "OrangePlanet, 4th Floor, Gangnam-gu, Seoul",
    "name": "OrangePlanet",
    "lat": 37.58827,
    "lon": 126.98944
  },
  "seoul::Cafe en Travel, 45 Gangnam-daero 102-gil, Gangnam-gu, Seoul": {
    "venue": "Cafe en Travel, 45 Gangnam-daero 102-gil, Gangnam-gu, Seoul",
    "name": "Cafe en Travel",
    "lat": 37.56671,
    "lon": 126.99044
  },
  "seoul::Sebasi Demaco Hall, B1, 16 Teheran-ro 53-gil, Gangnam-gu, Seoul": {
    "venue": "Sebasi Demaco Hall, B1, 16 Teheran-ro 53-gil, Gangnam-gu, Seoul",
    "name": "Sebasi Demaco Hall",
    "lat": 37.5778,
    "lon": 126.96019
  },
  "seoul::Allday Sound Bar, 34 Dosan-daero 11-gil, Gangnam-gu, Seoul": {
    "venue": "Allday Sound Bar, 34 Dosan-daero 11-gil, Gangnam-gu, Seoul",
    "name": "Allday Sound Bar",
    "lat": 37.55412,
    "lon": 126.96058
  },
  "singapore::foodpanda SG, 63 Robinson Road, Singapore": {
    "venue": "foodpanda SG, 63 Robinson Road, Singapore",
    "name": "foodpanda SG",
    "lat": 1.36171,
    "lon": 103.79815
  },
  "singapore::Open Sourced, 10A Perak Rd, Rochor, Singapore": {
    "venue": "Open Sourced, 10A Perak Rd, Rochor, Singapore",
    "name": "Open Sourced",
    "lat": 1.36272,
    "lon": 103.81411
  },
  "singapore::Open Sourced, 10A Perak Rd, Singapore": {
    "venue": "Open Sourced, 10A Perak Rd, Singapore",
    "name": "Open Sourced",
    "lat": 1.33125,
    "lon": 103.79646
  },
  "singapore::Space99, 606 Serangoon Rd, Singapore 218214": {
    "venue": "Space99, 606 Serangoon Rd, Singapore 218214",
    "name": "Space99",
    "lat": 1.38154,
    "lon": 103.84516
  },
  "singapore::Room2F | Events & Gallery Space, 231 Bras Basah Complex, Singapore": {
    "venue": "Room2F | Events & Gallery Space, 231 Bras Basah Complex, Singapore",
    "name": "Room2F | Events & Gallery Space",
    "lat": 1.37217,
    "lon": 103.79388
  },
  "singapore::Traveloka Services Pte. Ltd., Robinson 77, Singapore": {
    "venue": "Traveloka Services Pte. Ltd., Robinson 77, Singapore",
    "name": "Traveloka Services Pte. Ltd.",
    "lat": 1.33883,
    "lon": 103.79237
  },
  "singapore::ShopBack SG, 65 Pasir Panjang Rd, Singapore": {
    "venue": "ShopBack SG, 65 Pasir Panjang Rd, Singapore",
    "name": "ShopBack SG",
    "lat": 1.33455,
    "lon": 103.81802
  },
  "singapore::Hyper Island Asia, 991B Alexandra Rd, Singapore": {
    "venue": "Hyper Island Asia, 991B Alexandra Rd, Singapore",
    "name": "Hyper Island Asia",
    "lat": 1.37886,
    "lon": 103.80254
  },
  "singapore::WeWork, 21 Collyer Quay, Singapore": {
    "venue": "WeWork, 21 Collyer Quay, Singapore",
    "name": "WeWork",
    "lat": 1.33506,
    "lon": 103.79953
  },
  "singapore::OCBC Campus, 260 Tg Pagar Rd, Singapore": {
    "venue": "OCBC Campus, 260 Tg Pagar Rd, Singapore",
    "name": "OCBC Campus",
    "lat": 1.36272,
    "lon": 103.82257
  },
  "singapore::The Great Room, 18th Floor, Centennial Tower, Singapore": {
    "venue": "The Great Room, 18th Floor, Centennial Tower, Singapore",
    "name": "The Great Room",
    "lat": 1.38206,
    "lon": 103.82781
  },
  "singapore::Spenmo, 15A Duxton Hill, Singapore": {
    "venue": "Spenmo, 15A Duxton Hill, Singapore",
    "name": "Spenmo",
    "lat": 1.36085,
    "lon": 103.81692
  },
  "singapore::Super Loco Robertson Quay, 60 Robertson Quay, Singapore": {
    "venue": "Super Loco Robertson Quay, 60 Robertson Quay, Singapore",
    "name": "Super Loco Robertson Quay",
    "lat": 1.33189,
    "lon": 103.8084
  },
  "stockholm::Solita Ab, Lästmakargatan 10, Stockholm": {
    "venue": "Solita Ab, Lästmakargatan 10, Stockholm",
    "name": "Solita Ab",
    "lat": 59.32176,
    "lon": 18.05731
  },
  "stockholm::Regeringsgatan 25, Stockholm": {
    "venue": "Regeringsgatan 25, Stockholm",
    "name": "Regeringsgatan 25",
    "lat": 59.3377,
    "lon": 18.04606
  },
  "swiss::EF Education AG, Selnaustrasse 30, Zürich": {
    "venue": "EF Education AG, Selnaustrasse 30, Zürich",
    "name": "EF Education AG",
    "lat": 47.35662,
    "lon": 8.53793
  },
  "swiss::Spaces - Zurich, Bleicherweg 10, Zürich": {
    "venue": "Spaces - Zurich, Bleicherweg 10, Zürich",
    "name": "Spaces - Zurich",
    "lat": 47.35518,
    "lon": 8.56953
  },
  "swiss::Quai de l'Ile 13, Genève": {
    "venue": "Quai de l'Ile 13, Genève",
    "name": "Quai de l'Ile 13",
    "lat": 47.38877,
    "lon": 8.55376
  },
  "swiss::Pl. de la Gare 12, Lausanne": {
    "venue": "Pl. de la Gare 12, Lausanne",
    "name": "Pl. de la Gare 12",
    "lat": 47.37448,
    "lon": 8.52966
  },
  "sydney::Mantel Group, Level 21, 580 George Street, Sydney NSW 2000": {
    "venue": "Mantel Group, Level 21, 580 George Street, Sydney NSW 2000",
    "name": "Mantel Group",
    "lat": -33.85934,
    "lon": 151.21097
  },
  "sydney::Mantel Group, 580 George St, Sydney NSW 2000": {
    "venue": "Mantel Group, 580 George St, Sydney NSW 2000",
    "name": "Mantel Group",
    "lat": -33.87364,
    "lon": 151.19613
  },
  "sydney::CBA Foundry, 1 Locomotive St, Eveleigh, NSW": {
    "venue": "CBA Foundry, 1 Locomotive St, Eveleigh, NSW",
    "name": "CBA Foundry",
    "lat": -33.88359,
    "lon": 151.22989
  },
  "sydney::Rokt, 300 Elizabeth St, Surry Hills, NSW": {
    "venue": "Rokt, 300 Elizabeth St, Surry Hills, NSW",
    "name": "Rokt",
    "lat": -33.8977,
    "lon": 151.20158
  },
  "sydney::Nearmap, Barangaroo, NSW": {
    "venue": "Nearmap, Barangaroo, NSW",
    "name": "Nearmap",
    "lat": -33.85787,
    "lon": 151.22815
  },
  "sydney::SafetyCulture, 72 Foveaux St, Surry Hills, NSW": {
    "venue": "SafetyCulture, 72 Foveaux St, Surry Hills, NSW",
    "name": "SafetyCulture",
    "lat": -33.83934,
    "lon": 151.22654
  },
  "sydney::Assembly Payments, Level 12, 201 Kent Street, Sydney": {
    "venue": "Assembly Payments, Level 12, 201 Kent Street, Sydney",
    "name": "Assembly Payments",
    "lat": -33.87574,
    "lon": 151.19764
  },
  "sydney::Canva, 110 Kippax St, Surry Hills, NSW": {
    "venue": "Canva, 110 Kippax St, Surry Hills, NSW",
    "name": "Canva",
    "lat": -33.87693,
    "lon": 151.22698
  },
  "sydney::Thoughtworks, 50 Carrington St, Sydney": {
    "venue": "Thoughtworks, 50 Carrington St, Sydney",
    "name": "Thoughtworks",
    "lat": -33.84289,
    "lon": 151.2201
  },
  "sydney::Microsoft Reactor Sydney, 11 York St, Sydney": {
    "venue": "Microsoft Reactor Sydney, 11 York St, Sydney",
    "name": "Microsoft Reactor Sydney",
    "lat": -33.87562,
    "lon": 151.22168
  },
  "taipei::DCard, 台北市大安區光復南路102號14樓, Taipei": {
    "venue": "DCard, 台北市大安區光復南路102號14樓, Taipei",
    "name": "DCard",
    "lat": 25.02661,
    "lon": 121.56018
  },
  "taipei::DCard, 台北市大安區光復南路102號14樓 (originally 14樓, moved to 5樓 due to projector issue, then back to 14樓), Taipei": {
    "venue": "DCard, 台北市大安區光復南路102號14樓 (originally 14樓, moved to 5樓 due to projector issue, then back to 14樓), Taipei",
    "name": "DCard",
    "lat": 25.02591,
    "lon": 121.54896
  },
  "taipei::Dcard office, 台北市大安區光復南路102號14樓, Taipei": {
    "venue": "Dcard office, 台北市大安區光復南路102號14樓, Taipei",
    "name": "Dcard office",
    "lat": 25.00715,
    "lon": 121.56884
  },
  "taipei::AppWorks School, 台北市仁愛路二段99號10樓, Taipei": {
    "venue": "AppWorks School, 台北市仁愛路二段99號10樓, Taipei",
    "name": "AppWorks School",
    "lat": 25.0113,
    "lon": 121.55327
  },
  "taipei::均一教育平台, No. 25, Baoqing Rd, Zhongzheng District, Taipei": {
    "venue": "均一教育平台, No. 25, Baoqing Rd, Zhongzheng District, Taipei",
    "name": "均一教育平台",
    "lat": 25.04818,
    "lon": 121.59293
  },
  "taipei::Partipost office, 104 台北市中山區中山北路二段20巷16號, Taipei": {
    "venue": "Partipost office, 104 台北市中山區中山北路二段20巷16號, Taipei",
    "name": "Partipost office",
    "lat": 25.03008,
    "lon": 121.57731
  },
  "taipei::Dcard, 台北市大安區光復南路102號14樓, Taipei": {
    "venue": "Dcard, 台北市大安區光復南路102號14樓, Taipei",
    "name": "Dcard",
    "lat": 25.06017,
    "lon": 121.53977
  },
  "taipei::iCHEF office, 106465 台北市大安區仁愛路三段136號15樓, Taipei": {
    "venue": "iCHEF office, 106465 台北市大安區仁愛路三段136號15樓, Taipei",
    "name": "iCHEF office",
    "lat": 25.05919,
    "lon": 121.56055
  },
  "taipei::Gandi 內湖辦公室, 台北市內湖區洲子街196號6樓, Taipei": {
    "venue": "Gandi 內湖辦公室, 台北市內湖區洲子街196號6樓, Taipei",
    "name": "Gandi 內湖辦公室",
    "lat": 25.02113,
    "lon": 121.58444
  },
  "taipei::Mozilla Community Space Taipei, 100, Taipei City, Zhongzheng District, Section 1, Bade Rd, No. 94, 3F, Taipei": {
    "venue": "Mozilla Community Space Taipei, 100, Taipei City, Zhongzheng District, Section 1, Bade Rd, No. 94, 3F, Taipei",
    "name": "Mozilla Community Space Taipei",
    "lat": 25.06016,
    "lon": 121.55879
  },
  "taipei::Garage+, 台北市中山區中山北路二段96號後棟9樓918室, Taipei": {
    "venue": "Garage+, 台北市中山區中山北路二段96號後棟9樓918室, Taipei",
    "name": "Garage+",
    "lat": 25.0341,
    "lon": 121.5443
  },
  "tel-aviv::monday.com, Yitzhak Sadeh St 6, Tel Aviv-Yafo": {
    "venue": "monday.com, Yitzhak Sadeh St 6, Tel Aviv-Yafo",
    "name": "monday.com",
    "lat": 32.08071,
    "lon": 34.75383
  },
  "tel-aviv::Elementor, Tuval 40, floor 15, Ramat Gan": {
    "venue": "Elementor, Tuval 40, floor 15, Ramat Gan",
    "name": "Elementor",
    "lat": 32.11388,
    "lon": 34.77166
  },
  "tokyo::DATUM STUDIO Inc. (Meguro HQ), Meguro Arco Tower 16F, Shimo-Meguro 1-8-1, Meguro City, Tokyo": {
    "venue": "DATUM STUDIO Inc. (Meguro HQ), Meguro Arco Tower 16F, Shimo-Meguro 1-8-1, Meguro City, Tokyo",
    "name": "DATUM STUDIO Inc. (Meguro HQ)",
    "lat": 35.66304,
    "lon": 139.66117
  },
  "tokyo::primeNumber Inc., JR Toku Meguro Building 5F, Kamiosaki 3-1-1, Shinagawa City, Tokyo": {
    "venue": "primeNumber Inc., JR Toku Meguro Building 5F, Kamiosaki 3-1-1, Shinagawa City, Tokyo",
    "name": "primeNumber Inc.",
    "lat": 35.69462,
    "lon": 139.65495
  },
  "tokyo::Yappli Inc. Tokyo Office, Sumitomo Fudosan Roppongi Grand Tower 41F, Roppongi 3-2-1, Minato City, Tokyo": {
    "venue": "Yappli Inc. Tokyo Office, Sumitomo Fudosan Roppongi Grand Tower 41F, Roppongi 3-2-1, Minato City, Tokyo",
    "name": "Yappli Inc. Tokyo Office",
    "lat": 35.69299,
    "lon": 139.65935
  },
  "tokyo::Classmethod Inc. office, Hibiya Fort Tower 26F, Nishishimbashi 1-1-1, Minato City, Tokyo": {
    "venue": "Classmethod Inc. office, Hibiya Fort Tower 26F, Nishishimbashi 1-1-1, Minato City, Tokyo",
    "name": "Classmethod Inc. office",
    "lat": 35.67915,
    "lon": 139.62217
  },
  "tokyo::CARTA HOLDINGS Inc. HQ, Toranomon Hills Station Tower 36F, Toranomon 2-6-1, Minato City, Tokyo": {
    "venue": "CARTA HOLDINGS Inc. HQ, Toranomon Hills Station Tower 36F, Toranomon 2-6-1, Minato City, Tokyo",
    "name": "CARTA HOLDINGS Inc. HQ",
    "lat": 35.65718,
    "lon": 139.62494
  },
  "tokyo::Timee Inc. Tokyo HQ, Shiodome City Center 35F, Higashi-Shimbashi 1-5-2, Minato City, Tokyo": {
    "venue": "Timee Inc. Tokyo HQ, Shiodome City Center 35F, Higashi-Shimbashi 1-5-2, Minato City, Tokyo",
    "name": "Timee Inc. Tokyo HQ",
    "lat": 35.65849,
    "lon": 139.67939
  },
  "tokyo::CARTA HOLDINGS Inc. HQ, Toranomon Hills Station Tower 36F, Toranomon, Minato City, Tokyo": {
    "venue": "CARTA HOLDINGS Inc. HQ, Toranomon Hills Station Tower 36F, Toranomon, Minato City, Tokyo",
    "name": "CARTA HOLDINGS Inc. HQ",
    "lat": 35.70058,
    "lon": 139.65436
  },
  "tokyo::DATUM STUDIO Inc., Toranomon Twin Building East Tower 12F, Toranomon 2-10-1, Minato City, Tokyo": {
    "venue": "DATUM STUDIO Inc., Toranomon Twin Building East Tower 12F, Toranomon 2-10-1, Minato City, Tokyo",
    "name": "DATUM STUDIO Inc.",
    "lat": 35.69623,
    "lon": 139.66905
  },
  "tokyo::MIXI Group Collaboration Space, Shibuya Scramble Square 36F, Shibuya 2-24-12, Shibuya City, Tokyo": {
    "venue": "MIXI Group Collaboration Space, Shibuya Scramble Square 36F, Shibuya 2-24-12, Shibuya City, Tokyo",
    "name": "MIXI Group Collaboration Space",
    "lat": 35.66744,
    "lon": 139.64268
  },
  "tokyo::CARTA HOLDINGS Inc. Shibuya Office, Shibuya Solasta 15F, Dogenzaka 1-21-1, Shibuya City, Tokyo": {
    "venue": "CARTA HOLDINGS Inc. Shibuya Office, Shibuya Solasta 15F, Dogenzaka 1-21-1, Shibuya City, Tokyo",
    "name": "CARTA HOLDINGS Inc. Shibuya Office",
    "lat": 35.70454,
    "lon": 139.64631
  },
  "toronto::OneEleven, 325 Front Street W, Suite 4, Toronto, ON": {
    "venue": "OneEleven, 325 Front Street W, Suite 4, Toronto, ON",
    "name": "OneEleven",
    "lat": 43.67222,
    "lon": -79.37735
  },
  "toronto::New Stadium, 83 Walnut Avenue, Toronto, ON": {
    "venue": "New Stadium, 83 Walnut Avenue, Toronto, ON",
    "name": "New Stadium",
    "lat": 43.67289,
    "lon": -79.36643
  },
  "toronto::Village by the Grange Food Court, 105 McCaul Street, Toronto, ON": {
    "venue": "Village by the Grange Food Court, 105 McCaul Street, Toronto, ON",
    "name": "Village by the Grange Food Court",
    "lat": 43.62679,
    "lon": -79.40614
  },
  "uyo::theBUNKer Uyo, 32 B G Bassey Ave, Uyo": {
    "venue": "theBUNKer Uyo, 32 B G Bassey Ave, Uyo",
    "name": "theBUNKer Uyo",
    "lat": 5.01517,
    "lon": 7.903
  },
  "uyo::Future Labs, 3 Chubb Rd, Ikot Ekpene, Akwa Ibom": {
    "venue": "Future Labs, 3 Chubb Rd, Ikot Ekpene, Akwa Ibom",
    "name": "Future Labs",
    "lat": 5.06042,
    "lon": 7.93216
  },
  "vancouver::Talk Shop Media, 1498 W 5th Ave, Vancouver, BC": {
    "venue": "Talk Shop Media, 1498 W 5th Ave, Vancouver, BC",
    "name": "Talk Shop Media",
    "lat": 49.29817,
    "lon": -123.10696
  },
  "vienna::Sclable Business Solutions GmbH, Marc-Aurel-Straße 10-12, Vienna": {
    "venue": "Sclable Business Solutions GmbH, Marc-Aurel-Straße 10-12, Vienna",
    "name": "Sclable Business Solutions GmbH",
    "lat": 48.22458,
    "lon": 16.37081
  },
  "vienna::MeisterLabs, Mariahilferstraße 97/4, Vienna": {
    "venue": "MeisterLabs, Mariahilferstraße 97/4, Vienna",
    "name": "MeisterLabs",
    "lat": 48.185,
    "lon": 16.40014
  },
  "vilnius::Cyber City Building C, Švitrigailos str. 32, Vilnius, Lithuania": {
    "venue": "Cyber City Building C, Švitrigailos str. 32, Vilnius, Lithuania",
    "name": "Cyber City Building C",
    "lat": 54.71143,
    "lon": 25.26845
  },
  "vilnius::Vinted Vilnius HQ, Švitrigailos 13, Vilnius": {
    "venue": "Vinted Vilnius HQ, Švitrigailos 13, Vilnius",
    "name": "Vinted Vilnius HQ",
    "lat": 54.67156,
    "lon": 25.29436
  },
  "wellington::Qrious (Spark), Level One, 42-52 Willis Street, Wellington": {
    "venue": "Qrious (Spark), Level One, 42-52 Willis Street, Wellington",
    "name": "Qrious (Spark)",
    "lat": -41.2642,
    "lon": 174.75142
  }
}
